-- =====================================================================
-- 003_seed_muscle_map.sql  --  Editable eid -> muscle/movement lookup.
-- Auto-generated by classifying canonical exercise names, then hand-
-- correct as needed. Loader re-applies this with ON CONFLICT DO NOTHING
-- and adds any NEW eids via its keyword classifier, so YOUR edits here
-- (and in the table) survive a full --truncate refresh.
--
-- To correct one:  UPDATE workout.exercise_muscle_map
--                  SET muscle_group='back', movement='pull', is_compound=true
--                  WHERE eid = 21;
-- =====================================================================

INSERT INTO workout.exercise_muscle_map (eid, muscle_group, movement, is_compound) VALUES
  (   1, 'chest', 'push', true),  -- Barbell bar push up
  (   2, 'chest', 'push', true),  -- Barbell Bench Press
  (   3, 'back', 'pull', true),  -- Barbell Bent-Over Row
  (   4, 'chest', 'push', true),  -- Barbell Bench Press (Close Grip)
  (   5, 'chest', 'push', true),  -- Barbell Decline Bench Press
  (   6, 'shoulders', 'push', false),  -- Barbell Front Raise
  (   7, 'hamstrings', 'legs', false),  -- Barbell Good Morning
  (   8, 'chest', 'push', true),  -- Barbell Incline Bench Press
  (   9, 'glutes', 'legs', false),  -- Thigh abduction
  (  10, 'shoulders', 'push', true),  -- Barbell Shoulder Press
  (  11, 'traps', 'pull', false),  -- Barbell Shrug
  (  12, 'quads', 'legs', true),  -- Barbell Squat
  (  13, 'traps', 'pull', false),  -- Barbell Upright Row
  (  14, 'chest', 'push', false),  -- Cable Cross-Over
  (  15, 'shoulders', 'push', false),  -- Smith machine 1 arm shoulder raise
  (  16, 'back', 'pull', true),  -- Row Grip Chest Pull
  (  17, 'shoulders', 'push', false),  -- Casket raiser
  (  18, 'glutes', 'legs', false),  -- Standing Abductor
  (  19, 'back', 'pull', true),  -- Archer pulls
  (  21, 'back', 'pull', true),  -- Cable Seated Row
  (  25, 'shoulders', 'push', true),  -- Dumbbell Seated Arnold Press
  (  26, 'chest', 'push', true),  -- Dumbbell Bench Press
  (  31, 'chest', 'push', true),  -- Dumbbell Incline Bench Press
  (  32, 'shoulders', 'push', false),  -- Dumbbell Lateral Raise
  (  35, 'shoulders', 'push', true),  -- Dumbbell One-Arm Shoulder Press
  (  41, 'chest', 'push', false),  -- Dumbbell Fly
  (  42, 'traps', 'pull', false),  -- Dumbbell Shoulder Shrug
  (  45, 'chest', 'push', false),  -- Machine Fly
  (  46, 'shoulders', 'push', true),  -- Machine Shoulder Press
  (  48, 'shoulders', 'push', true),  -- Dumbbell Seated Shoulder Press
  (  50, 'traps', 'pull', false),  -- Smith Machine Shrug
  (  52, 'back', 'pull', true),  -- T Bar Row
  (  56, 'abs', 'core', false),  -- Machine Ab Crunch
  (  61, 'abs', 'core', false),  -- Hanging Leg Raise
  (  78, 'abs', 'core', false),  -- Decline Crunch
  (  80, 'abs', 'core', false),  -- Dumbbell Side Bend
  (  86, 'back', 'pull', true),  -- Cable Lat Pulldown (Wide Grip)
  (  90, 'back', 'pull', true),  -- Dumbbell One-Arm Row
  (  92, 'back', 'pull', false),  -- Back Hyperextension
  (  93, 'hamstrings', 'legs', true),  -- Barbell Deadlift
  (  95, 'biceps', 'pull', false),  -- EZ Bar Curl
  (  98, 'biceps', 'pull', false),  -- Dumbbell Hammer Curl (Cross Body)
  ( 100, 'biceps', 'pull', false),  -- Dumbbell Bicep Curl
  ( 102, 'biceps', 'pull', false),  -- Cable Bicep Curl
  ( 106, 'biceps', 'pull', false),  -- Dumbbell Incline Curl
  ( 107, 'biceps', 'pull', false),  -- Dumbbell Concentration Curl
  ( 108, 'biceps', 'pull', false),  -- Dumbbell Hammer Curl
  ( 111, 'forearms', 'pull', false),  -- Barbell Reverse Curl
  ( 112, 'biceps', 'pull', false),  -- Barbell Curl
  ( 113, 'biceps', 'pull', false),  -- Barbell Preacher Curl
  ( 114, 'biceps', 'pull', false),  -- Dumbbell Alternating Hammer Curl
  ( 116, 'biceps', 'pull', false),  -- Dumbbell Alternating Bicep Curl
  ( 117, 'forearms', 'pull', false),  -- Barbell Wrist Curl (Posterior)
  ( 118, 'forearms', 'pull', false),  -- Dumbbell Wrist Curl (Palms Up)
  ( 120, 'forearms', 'pull', false),  -- Wrist Roller
  ( 123, 'forearms', 'pull', false),  -- Dumbbell Wrist Curl (Palms Down)
  ( 127, 'quads', 'legs', true),  -- Hack Squat
  ( 130, 'quads', 'legs', false),  -- Machine Leg Extension
  ( 132, 'quads', 'legs', true),  -- Machine Leg Press
  ( 135, 'quads', 'legs', true),  -- Smith Machine Squat
  ( 140, 'calves', 'legs', false),  -- Calf Press On Leg Press
  ( 142, 'calves', 'legs', false),  -- Dumbbell Calf Raise
  ( 144, 'calves', 'legs', false),  -- Machine Seated Calf Raise
  ( 149, 'triceps', 'push', false),  -- Cable Tricep Pushdown (V-Bar)
  ( 155, 'triceps', 'push', false),  -- Cable Rope Overhead Tricep Extension
  ( 157, 'triceps', 'push', false),  -- Cable One-Arm Tricep Pushdown (Reverse Grip)
  ( 158, 'triceps', 'push', false),  -- Dumbbell Seated Tricep Press
  ( 159, 'triceps', 'push', false),  -- Cable Tricep Pushdown (Rope)
  ( 160, 'hamstrings', 'legs', false),  -- Machine Leg Curl (Prone)
  ( 161, 'hamstrings', 'legs', false),  -- Machine Seated Leg Curl
  ( 165, 'chest', 'push', false),  -- Dumbbell Incline Fly
  ( 176, 'chest', 'push', true),  -- Barbell Wide Grip Bench Press
  ( 178, 'chest', 'push', true),  -- Machine Incline Chest Press
  ( 183, 'shoulders', 'push', false),  -- Cable Shoulder Extension
  ( 199, 'hamstrings', 'legs', false),  -- Barbell Romanian Deadlift
  ( 216, 'glutes', 'legs', false),  -- Machine Hip Abduction
  ( 217, 'glutes', 'legs', false),  -- Machine Hip Adduction
  ( 221, 'triceps', 'push', false),  -- EZ Bar Tricep Extension
  ( 225, 'triceps', 'push', false),  -- Cable One-Arm Tricep Pushdown (Reverse Grip)
  ( 247, 'triceps', 'push', false),  -- Dumbbell Tricep Extension
  ( 250, 'shoulders', 'push', false),  -- Cable Shoulder Extension
  ( 253, 'triceps', 'push', false),  -- Machine Tricep Extension
  ( 271, 'biceps', 'pull', false),  -- Preacher Curl Machine
  ( 296, 'calves', 'legs', false),  -- Smith Machine Reverse Calf Raise
  ( 366, 'biceps', 'pull', false),  -- Dumbbell Inner Bicep Curl
  ( 368, 'shoulders', 'push', false),  -- Dumbbell Around the World
  ( 382, 'forearms', 'pull', false),  -- Dumbbell Supinated One-Arm Wrist Curl
  ( 386, 'glutes', 'legs', false),  -- Barbell Hip Thrust
  ( 413, 'shoulders', 'push', false),  -- Dumbbell Front Raise
  ( 479, 'quads', 'legs', true),  -- Kettlebell Goblet Squat
  ( 486, 'quads', 'legs', true),  -- Machine Leg Press (Narrow Stance)
  ( 700, 'back', 'pull', true),  -- Machine Seated Row
  ( 770, 'shoulders', 'push', false),  -- Machine Lateral Shoulder Raise
  ( 794, 'abs', 'core', false),  -- Cable Pallof Press with Rotation
  ( 805, 'biceps', 'pull', false),  -- Machine Hammer Curl
  ( 807, 'back', 'pull', true),  -- Barbell Row
  ( 829, 'back', 'pull', true),  -- Barbell Rack Pull
  ( 874, 'rear delts', 'pull', false),  -- Cable Rope Face Pull
  ( 878, 'chest', 'push', false),  -- Machine Reverse Fly
  ( 884, 'shoulders', 'push', true),  -- Dumbbell Shoulder Press
  (1010, 'biceps', 'pull', false),  -- Dumbbell Alternating Seated Curl
  (1011, 'biceps', 'pull', false),  -- Dumbbell Seated Alternating Hammer Curl
  (1029, 'biceps', 'pull', false),  -- Dumbbell Seated Hammer Curl
  (1037, 'back', 'pull', true),  -- Barbell Incline Bench Row
  (1050, 'back', 'pull', true),  -- Cable Rope Seated Row
  (1052, 'back', 'pull', true),  -- Cable One-Arm Row
  (1056, 'chest', 'push', false),  -- Cable Straight Arm Crossover
  (1057, 'chest', 'push', false),  -- Cable Mid Chest Crossover
  (1074, 'forearms', 'pull', false),  -- EZ Bar Curl (Reverse Grip)
  (1122, 'shoulders', 'push', true),  -- Dumbbell Arnold Press
  (1171, 'triceps', 'push', false),  -- Cable Rope High Pulley Tricep Extension
  (1179, 'triceps', 'push', false),  -- Cable One-Arm Tricep Extension
  (1249, 'forearms', 'pull', false),  -- Machine Bicep Curl (Reverse Grip)
  (1254, 'calves', 'legs', false),  -- Machine Calf Press
  (1259, 'back', 'pull', false),  -- Machine Back Extension
  (1268, 'back', 'pull', true),  -- Machine Lat Pulldown
  (1270, 'chest', 'push', true),  -- Machine Inner Chest Press
  (1309, 'quads', 'legs', true),  -- Machine Leg Press (Wide Stance)
  (1311, 'back', 'pull', true),  -- Machine Reverse T Bar Row
  (1320, 'forearms', 'pull', false),  -- Dumbbell Seated Wrist Curl
  (1334, 'triceps', 'push', false),  -- Cable One-Arm Tricep Pushdown
  (1432, 'quads', 'legs', true)  -- Bodyweight Sumo Squat
ON CONFLICT (eid) DO NOTHING;
